# Generated by Django 3.2.9 on 2022-01-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='choice')),
                ('is_correct', models.BooleanField(verbose_name='is correct')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
            ],
        ),
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.CreateModel(
            name='AnswersDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizdto')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questiondto')),
            ],
        ),
    ]
